- name: debug item
  debug:
    var: "{{item.host | ipaddr}}"
    verbosity: 3


- name: ReDiscover a device, conflict resolve with default policy
  bigiq_device_discovery:
    device_address: "{{item.host | ipaddr}}"
    modules:
      - ltm
    force: yes
    provider: "{{provider}}"

